parameters:
- name: versionOption
  type: string
  default: patch
  displayName: 'The semantic version type (major, minor, or patch)'

name: layer-keyvault-$(Date:yyyyMMdd).$(Rev:rr)

trigger:
  branches:
    include:
    - users/*
  paths:
    include:
      - /layers/keyvault
      - /scripts
    exclude: 
      - /**/*.md
      - /.attachments

variables:
  - name: system.debug 
    value: true
  - name: downloadPath
    value: $(Build.ArtifactStagingDirectory)
  - name: layerName
    value: keyvault

pool:
    vmImage: 'ubuntu-latest'

steps:
- template: /layers/Version.yaml
  parameters:
    layerName: ${{ variables.layerName}}
    versionOption: ${{ parameters.versionOption }}
        # this variable will be instantiated from an upstream pipeline named manual-version-layers
        # at https://dev.azure.com/StratumKit/Stratum/_build?definitionId=430&_a=summary
    triggerPipelineVersionOption: "$(triggerPipelineVersionOption)"
